### ISSUE TITLE
Usage example ?

### ISSUE THREAD

**Issue by eobeda** [carlescs/itsUtils#1]
I was looking for additional documentation on how to use your code. Can you provide some sample code or direct me to where I might be able to find some ?

If it makes a difference, I am using the iTextSharp (ver:5.4.5) 'PdfWriter' with the ParseXHtml method of the XMLWorkerHelper object to convert HTML into PDF.

Thanks in advance for the help
Ed

**Comment by carlescs** [comment]
Sorry for the late reply.

You need to assign my CustomPageEvent to the page event property of the PdfWriter. In the constructor of my PageEvent you can define the options so that a background watermark is shown or the page numbers and alignment for the page numbers.
